### PR TITLE
Phrase entity type

### PR DESCRIPTION
**Pull request by ad2476**
Addresses an ambiguity surrounding `Line`: Depending on the underlying OCR engine, `Line` entities can have different definitions. MSRAPI v3 seems to return "lines" which are contiguous sequences of words on the same line, while other OCR engines may simply return "lines" consisting of a horizontal scan line of words in an image.

In order to distinguish "sequences of words contiguous on the same line" from the more ambiguous "OCR line", this PR introduces a `Phrase` entity type which guarantees that invariant. On the other hand, we could just directly enforce that invariant on `Line` and do away with the need for `Phrase` but that might confuse people writing converters from OCR output to foundation types.

In the case where OCR lines mean the same thing conveyed by `Phrase`, it's up to the user of Foundation to choose what they want to get as entities. (@andrey-ib not to be too Blueprint-specific, but this would let us trivially cast `Line`s from MSRAPI to `Phrase`, or construct `Phrase`s via clustering/etc when we don't have MSRAPI lines, in the entity generation step -- the idea is for Blueprint not to know/care what OCR engine our `Line` entities came from)

Also renames `Entity.ocr_words()` to `Entity.words()`, to reflect the previous renaming of `OcrWordEntity` to `Word`.

### CODE REVIEW

**Review by vontell — APPROVED** [review]
Thanks for the extensive comments! This looks good to me.

**Review by andrey-ib — COMMENTED** [review]
I don't see why we need both -- what you are calling a line seems useless, the equivalent of a column of words. If a horizontally-arranged row of words is semantically tied together then it should be a phrase (or a table row or something).

**Comment by ad2476** [comment]
> I don't see why we need both -- what you are calling a line seems useless, the equivalent of a column of words. If a horizontally-arranged row of words is semantically tied together then it should be a phrase (or a table row or something).

I agree with this, it would be better to redefine a line into something useful, and the name "phrase" does imply semantic relatedness. I'm not sure which approach would be least confusing -- I can definitely see a user of foundation expecting the `Line` entity to correspond exactly to the info coming out of OCR's lines.

**Comment by vontell** [comment]
@ad2476 @andrey-ib not sure if I entirely agree or I might just be misunderstanding. As a user of Foundation I have already encountered situations where there is a distinction between a Line and a Phrase (but yes maybe we can name them differently). For instance, MSFT OCR will return Lines and Phrases, while Abbyy only returns Lines. If we use only phrases, then I am not entirely sure how a user would figure out, for instance, how to construct a string for a set of phrases given that they would need to write quite a bit of code to construct lines from phrases based on pixel position.

Maybe a better description would be Line and LineSegment?

**Comment by andrey-ib** [comment]
When I have used MS OCR, it returns only words and something it calls
"lines", which correspond to what we in Foundation are calling "phrases".
Does this not match your experience with it?

**Comment by ad2476** [comment]
> As a user of Foundation I have already encountered situations where there is a distinction between a Line and a Phrase (but yes maybe we can name them differently). For instance, MSFT OCR will return Lines and Phrases, while Abbyy only returns Lines. If we use only phrases, then I am not entirely sure how a user would figure out, for instance, how to construct a string for a set of phrases given that they would need to write quite a bit of code to construct lines from phrases based on pixel position.

Yeah I'll clarify my comment to address the issues separately as I see them:
* It's important to distinguish between "OCR lines as a horizontal row of text spanning the entire image" and "A contiguous sequence of words on the same line, such that there's no significant whitespace between them". The introduction of a new data type such as `Phrase` would allow for Foundation to express that distinction.
* It's unclear whether we need to keep around the "OCR lines" if the sheer number of possible ways that can be interpreted results in the concept being mostly useless for all practical purposes. After all, if we don't really know what to expect in a `Line`, what's the point? On the other hand, foundation users might want to be able to pass around more "low-level" outputs of OCR, beyond just OCR words, and that would include "lines".
* In the case that we decide we don't need both (@andrey-ib 's position, I think?), it would probably make sense to enforce the "Sequence of contiguous words on the same line" invariant on `Line` directly.

> Maybe a better description would be Line and LineSegment?

* Lastly, the question is what to name this type. One of the harder problems in CS.

**Comment by andrey-ib** [comment]
I guess people will want lines of text sooner or later. Even though I don't
think it makes a lot of sense.

Phrases can also be multi-line in my mind.

**Pull request merged**
